FROM python:3.13.5

# Pythonの出力をバッファリングしないように設定（ログが見やすくなる）
ENV PYTHONUNBUFFERED=1

# コンテナ内のワーキングディレクトリを指定
WORKDIR /app

# matplotlibの日本語対応のフォントパッケージを先にインストール
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    fonts-ipaexfont \
    && rm -rf /var/lib/apt/lists/*

# wait-for-it.shをコンテナにコピー、実行権限を付与
COPY ./docker/Flask/wait-for-it.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/wait-for-it.sh

# カレントディレクトリのrequirements.txtをワーキングディレクトリ直下にコピー
# 依存関係ファイルのみ先にコピー（キャッシュ効率化のため）
COPY requirements.txt .
COPY pytest.ini .

# pipをアップデートして、Pythonのパッケージをインストール
# ローカルの保存用ディレクトリ（キャッシュ）の影響を排除して、常に最新のパッケージをインストールしたいため、--no-cache-dirを採用
RUN pip install -U pip && \
    pip install --no-cache-dir -r requirements.txt

# コンテナにsrc, migration, wsgiをコピー
COPY ./src /app/src
COPY ./migrations /app/migrations
COPY ./wsgi.py /app/

# コンテナ実行時のコマンド
CMD ["/bin/sh", "-c", "flask db upgrade && gunicorn wsgi:app --bind 0.0.0.0:10000 --workers 4"]
