"""edit2_fields

Revision ID: 21d42bc05bde
Revises: 5a16ad135b46
Create Date: 2026-03-31 14:10:45.861187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d42bc05bde'
down_revision = '5a16ad135b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fieldname', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('fieldname')

    # ### end Alembic commands ###
