"""edit1_fields

Revision ID: 5a16ad135b46
Revises: d6f330a9544e
Create Date: 2026-03-31 14:10:11.366661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a16ad135b46'
down_revision = 'd6f330a9544e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('fieldname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fieldname', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=20), nullable=False))

    # ### end Alembic commands ###
