#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<EOSQL

CREATE ROLE $POSTGRES_TEST_USER WITH LOGIN PASSWORD '$POSTGRES_TEST_PASSWORD';
CREATE DATABASE $POSTGRES_TEST_DATABASE OWNER $POSTGRES_TEST_USER;

EOSQL