-- -- コンテナ初回起動時のテスト用DB、DBユーザーの作成
-- CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'pass1234'
-- CREATE USER IF NOT EXISTS 'testuser'@'%' IDENTIFIED BY 'test1234';
-- CREATE TABLE IF NOT EXISTS VSLog_db;
-- CREATE TABLE IF NOT EXISTS app_test;
-- GRANT ALL PRIVILEGES ON VSLog_db.* TO 'appuser'@'%';
-- GRANT ALL PRIVILEGES ON app_test.* TO 'testuser'@'%';
-- FLUSH PRIVILEGES;
